#!/usr/bin/env python
"""
demo_filter
4 june 2014

dent earl, dearl a soe ucsc edu

Demonstration of what a filter should look like.

"""
import sys
import lib_filter


def main():
  args = lib_filter.boilperplateArguments()
  # seq_dict = lib_filter.getSequences(args.sequence)
  # chrom_dict = lib_filter.getChromSizes(args.chromSizes)
  # for chrom in chrom_dict:
  #   assert(chrom_dict[chrom] == seq_dict[chrom].getLength())
  # for chrom in seq_dict:
  #   assert(chrom_dict[chrom] == seq_dict[chrom].getLength())


if __name__ == '__main__':
  main()
