#!/usr/bin/env python
"""
demo_filter
4 june 2014

dent earl, dearl a soe ucsc edu

Demonstration of what a filter should look like.

"""
from argparse import ArgumentParser
import sys


def InitializeArguments(parser):
  parser.add_argument('--refGenome')
  parser.add_argument('--genome')
  parser.add_argument('--geneCheckBed')
  parser.add_argument('--geneCheckBedDetails')
  parser.add_argument('--alignment')
  parser.add_argument('--sequence')
  parser.add_argument('--chromSizes')
  parser.add_argument('--outDir')


def CheckArguments(args, parser):
  pass


def main():
  parser = ArgumentParser()
  InitializeArguments(parser)
  args = parser.parse_args()
  CheckArguments(args, parser)
  sys.stdout.write('Call: %s %s %s %s %s %s %s %s %s\n'
                   % (sys.argv[0],
                      args.refGenome,
                      args.genome,
                      args.geneCheckBed,
                      args.geneCheckBedDetails,
                      args.alignment,
                      args.sequence,
                      args.chromSizes,
                      args.outDir,
                      ))


if __name__ == '__main__':
  main()
