#!/usr/bin/env python
"""
gigo garbage in, garbage out.
23 June 2014

dent earl, dearl a soe ucsc edu

a filter for the msca project analysis pipeline.
scans the original mm10 derived wgEncodeGencodeBasicVM2
gene-check output and marks all problem labels.
"""
import sys
import lib_filter


def createLabelSet(transcript):
  """ given a Transcript object, return a set of all of its labels.
  """
  labels = set()
  for a in transcript.annotations:
    for l in a.labels:
      labels.add(l)
  return labels


def main():
  args = lib_filter.boilerplateArguments()
  transcripts = lib_filter.getTranscripts(
    args.geneCheckBed, args.geneCheckBedDetails)
  originalTranscripts = lib_filter.getTranscripts(
    args.originalGeneCheckBed, args.originalGeneCheckBedDetails)
  originalTranscriptsDict = lib_filter.transcriptListToDict(
    originalTranscripts, noDuplicates=True)
  for t in transcripts:
    t_name = lib_filter.removeAlignmentNumber(t.name)
    if t_name not in originalTranscriptsDict:
      continue
    ot = originalTranscriptsDict[t_name]
    originalLabels = createLabelSet(ot)
    for annot in t.annotations:
      newLabels = []
      for label in annot.labels:
        if label in originalLabels:
          # ^ character means an original label
          newLabels.append('^%s' % label)
        else:
          newLabels.append(label)
      annot.labels = newLabels
  lib_filter.writeAllBeds(transcripts, args)


if __name__ == '__main__':
  main()
