#!/usr/bin/env python
"""Labels exonic indels relative to the reference on the transcripts
and fixes false "introns" that get created on insertions.

Known issues:
- indels on exon boundaries won't be annotated.
"""
import sys
from collections import defaultdict
import lib_filter

def labelInsertions(original_transcript, transcript, alignment):
    """Label any insertions in the target's exons and return a list of
    chromosomeIntervals representing the insertions."""
    ret = [] # will be a list of insertions
    queryTranscriptSize = reduce(lambda a, e: a + e.stop - e.start, original_transcript.exons, 0)
    assert queryTranscriptSize > 0
    # Need to find the exon sizes since we are iterating along the
    # spliced transcript and need to know when to ignore "insertions"
    # that are actually introns.
    exonSizes = [e.stop - e.start for e in original_transcript.exons]
    if not original_transcript.chromosomeInterval.strand:
        exonSizes.reverse()
    # transcript-relative exon boundaries.
    exonStarts = reduce(lambda a, es: a + [a[-1] + es], exonSizes, [0])
    prevTargetPos = None
    for query_i in xrange(queryTranscriptSize):
        if query_i in exonStarts:
            # At the end of an intron--don't want to call an insertion.
            prevTargetPos = None
        target_i = alignment.queryCoordinateToTarget(query_i)
        if target_i is None:
            # Indicates a deletion.
            continue
        if prevTargetPos is not None and abs(target_i - prevTargetPos) != 1:
            # found an insertion.
            # Make sure this is a deletion and not some other crazy rearrangement.
            if transcript.chromosomeInterval.strand and target_i - prevTargetPos <= 0:
                sys.stderr.write("WARNING: crazy rearrangement on %s - jump from %d to %d\n" % (transcript.name, prevTargetPos, target_i))
                prevTargetPos = target_i
                continue
            elif not transcript.chromosomeInterval.strand and target_i - prevTargetPos >= 0:
                sys.stderr.write("WARNING: crazy rearrangement on %s - jump from %d to %d\n" % (transcript.name, prevTargetPos, target_i))
                prevTargetPos = target_i
                continue
            annotStart = min(prevTargetPos, target_i) + 1
            annotEnd = max(prevTargetPos, target_i)
            annotInterval = lib_filter.ChromosomeInterval(
                transcript.chromosomeInterval.chromosome,
                annotStart,
                annotEnd,
                transcript.chromosomeInterval.strand)
            annot = lib_filter.TranscriptAnnotation(
                annotInterval,
                transcript.name, [])
            annot.addLabel('insertion')
            # TODO: possibly add insertion length as an annotation.
            transcript.annotations.append(annot)
            ret.append(annotInterval)
        prevTargetPos = target_i
    return ret

def labelDeletions(original_transcript, transcript, alignment):
    """Label any deletions in the target's exons."""
    for exon in transcript.exons:
        prevQueryPos = None
        # We don't care much about transcript orientation here. We're
        # going backwards sometimes.
        for target_i in xrange(exon.start, exon.stop):
            # query_i is relative to query transcript start
            query_i = alignment.targetCoordinateToQuery(target_i)
            # If this is None, then the "intron on insertion" bug has
            # been fixed.
            if query_i is None:
                continue
            if prevQueryPos is not None and abs(query_i - prevQueryPos) != 1:
                # Just jumped past a deletion.
                # Make sure this is really a deletion and not some
                # crazy rearrangement, in which case we probably want
                # to detect it in a different filter.
                # NB: since the PSL query is the mRNA sequence, the
                # strand is always positive. So we check the *target*
                # strand to see if there's an inversion.
                if transcript.chromosomeInterval.strand:
                    if query_i - prevQueryPos <= 0:
                        sys.stderr.write("WARNING: looking for deletions, found crazy rearrangement on %s - jump from %d to %d\n" % (transcript.name, prevQueryPos, query_i))
                        prevQueryPos = query_i
                        continue
                else:
                    if query_i - prevQueryPos >= 0:
                        sys.stderr.write("WARNING: looking for deletions, found crazy rearrangement on %s - jump from %d to %d\n" % (transcript.name, prevQueryPos, query_i))
                        prevQueryPos = query_i
                        continue
                annot = lib_filter.TranscriptAnnotation(
                    lib_filter.ChromosomeInterval(
                        transcript.chromosomeInterval.chromosome,
                        target_i - 1 if transcript.chromosomeInterval.strand else target_i - 1,
                        target_i + 1 if transcript.chromosomeInterval.strand else target_i + 1,
                        transcript.chromosomeInterval.strand),
                    transcript.name, [])
                annot.addLabel('deletion')
                # TODO: maybe add deletion size here?
                transcript.annotations.append(annot)
            prevQueryPos = query_i

def deleteIntronsOnInsertions(transcript, insertions):
    """The transmap process makes small introns on all exonic
    insertions. In reality these are highly likely *not* to be introns
    and can change the predicted transcript substantially. Modify the
    transcript to seal up any introns that perfectly overlap an
    insertion.
    """
    introns = transcript.getIntrons()
    # check if an intron matches an insertion (there are only a few
    # insertions to compare with so, we iterate over the whole list for
    # every intron, although that may be a bit slower)
    for intron in introns:
        if intron in insertions:
            # traverse through the transcript and seal this gap.
            borderingExons = filter(lambda e: e.start == intron.stop or e.stop == intron.start, transcript.exons)
            assert len(borderingExons) == 2
            assert borderingExons[0].stop == intron.start
            assert borderingExons[1].start == intron.stop
            transcript.exons.remove(borderingExons[1])
            borderingExons[0].stop = borderingExons[1].stop

def removeInvalidUnknownSpliceTags(transcript, insertions):
    """Remove any unknownUtrSplice or unknownCdsSplice tags that don't
    cover an intron (probably because the intron has been removed.)"""
    introns = transcript.getIntrons()
    annotationsToRemove = set() # can't modify list during iteration.
    for annotation in transcript.annotations:
        if annotation.chromosomeInterval in introns:
            # This annotation covers an intron, ignore it
            continue
        for label in annotation.labels:
            if label in ('unknownUtrSplice', 'unknownCdsSplice'):
                assert annotation.chromosomeInterval in insertions
                annotationsToRemove.add(annotation)
    for annotation in annotationsToRemove:
        transcript.annotations.remove(annotation)

def extraArgs(parser):
    parser.add_argument('--noFixInsertions', help="Don't attempt to extend "
                        "transcripts over an insertion", action="store_true",
                        default=False)

def main():
    args = lib_filter.boilerplateArguments(extraArgs)

    transcripts = lib_filter.getTranscripts(
        args.geneCheckBed, args.geneCheckBedDetails)

    original_transcripts = lib_filter.getTranscripts(
        args.originalGeneCheckBed, args.originalGeneCheckBedDetails)
    original_transcripts_dict = lib_filter.transcriptListToDict(
      original_transcripts, noDuplicates=True)

    alignments = lib_filter.getAlignments(args.alignment)
    # label alignments so we can easily access them later (the
    # transcript name and target chrom is unambiguous)
    alignments_dict = defaultdict(list)
    for a in alignments:
        alignments_dict[(a.qName, a.tName)].append(a)

    for transcript in transcripts:
        original_transcript = original_transcripts_dict[lib_filter.removeAlignmentNumber(transcript.name)]
        alignments = alignments_dict[(lib_filter.removeAlignmentNumber(transcript.name),
                                      transcript.chromosomeInterval.chromosome)]
        for alignment in alignments:
            insertions = labelInsertions(original_transcript, transcript, alignment)
            labelDeletions(original_transcript, transcript, alignment)
        if not args.noFixInsertions:
            # double negative, but, basically, fix insertions.
            deleteIntronsOnInsertions(transcript, insertions)
            removeInvalidUnknownSpliceTags(transcript, insertions)

    lib_filter.writeAllBeds(transcripts, args)

if __name__ == '__main__':
    main()
