#!/usr/bin/env python
"""
mRnaCompare
7 August 2014

dent earl, dearl a soe ucsc edu

a filter for the msca project analysis pipeline.
Compares the mRNA sequences between the genome in question
and the original species to look for synonymous and
nonsynonymous mutations.
"""
import numpy
import os
import sys
import lib_filter


class Counts(object):
  """ Object to store the number of things that happen during a single run.
  """
  def __init__(self):
    self.transcipts = 0
    self.o_transcipts = 0
    self.alignments = 0
    self.seqs = 0
    self.o_seqs = 0
    self.dropped_singleExons = 0
    self.dropped_missingSeqs = 0
    self.dropped_o_missingSeqs = 0
    self.dropped_mRnaNs = 0
    self.dropped_matchingMRna = 0
    self.dropped_emptyAASeq = 0
    self.dropped_noStart = 0
    self.dropped_noStop = 0
    self.aaSeqLens = []
    self.dropped_aaSeqTooShort = 0
    self.walkAlignment = 0
    self.dropped_alignmentNoCoverGene = 0
    self.walkMRna = 0
  def recordCounts(self, args):
    variables_0 = ['transcripts', 'o_transcripts', 'alignments', 'seqs',
                   'o_seqs', 'dropped_singleExons', 'dropped_missingSeqs',
                   'dropped_o_missingSeqs', 'dropped_mRnaNs',
                   'dropped_matchingMRna', 'dropped_emptyAASeq',
                   'dropped_noStart', 'dropped_noStop',
                   ]
    variables_1 = ['dropped_aaSeqTooShort', 'walkAlignment',
                   'dropped_alignmentNoCoverGene', 'walkMRna',
                   ]
    pairs_0 = [(name, getattr(self, name)) for name in variables_0]
    pairs_1 = [(name, getattr(self, name)) for name in variables_1]
    with open(os.path.join(args.outDir, 'counts.log'), 'w') as f:
      for name, value in pairs_0:
        f.write('%s %d (%.2f)\n' % (name, value,
                                    100 * float(value) / self.transcripts))
      f.write('aaSeqLens n %d min %d ave %.2f med %.1f max %d stdev %.2f\n' %
              (len(self.aaSeqLens), numpy.min(self.aaSeqLens),
               numpy.mean(self.aaSeqLens),
               numpy.median(self.aaSeqLens), numpy.max(self.aaSeqLens),
               numpy.std(self.aaSeqLens))
              )
      for name, value in pairs_1:
        f.write('%s %d\n' % (name, value))
      f.write('\n')
      for v in self.aaSeqLens:
        f.write('%f\n' % v)

def alignmentCoversGene(psl, t, mRNALength):
  """ Given a PSLRow object and a TRANSCRIPT object, determine
  if the PSL target range fits with where the MRNA is in the transcript.
  """
  mRna_left = min(t.mRnaCoordinateToChromosome(0),
                  t.mRnaCoordinateToChromosome(mRNALength - 1))
  mRna_right = max(t.mRnaCoordinateToChromosome(0),
                  t.mRnaCoordinateToChromosome(mRNALength - 1))
  if psl.tStart > mRna_left:
    return False
  if psl.tEnd < mRna_right:
    return False
  return True  # at the moment this isn't so much "True" as "Possibly"


def getCodon(transcript, codon_seq, codon_tup):
  """ Given a TRANSCRIPT, CODON_SEQ string, and CODON_TUP a tuple containing
  (codonNumber, withinCodonIndex), return the 3 nucleotide sequence
  corresponding to the CODON_TUP
  """
  if codon_tup is None: return None
  return codon_seq[codon_tup[0] * 3:codon_tup[0] * 3 + 3]


def recordOutOfFrame(a, t, ot, p, outOfFrameStart, numIndels):
  """ Having discovered the end of an outOfFrame, make a TranscriptAnnotation
  label for it.
  """
  start = min(outOfFrameStart, p)
  stop = max(outOfFrameStart, p) + 1
  ot_start = a.targetCoordinateToQuery(start)
  if a.strand == '+':
    inc = -1
  else:
    inc = 1
  while a.targetCoordinateToQuery(a.queryCoordinateToTarget(ot_start + inc)) is None:
    # back up the ot_start to the first instance of indel.
    # we know that there is a discontinuity in the query coordinates which
    # indicates that there should be some None alignments just before the
    # T START.
    ot_start += inc
    if ot_start < a.qStart or ot_start > a.qEnd:
      # it was Nones all the way down: give up
      ot_start = a.targetCoordinateToQuery(start)
      break
    assert(ot_start >= 0)
  ot_start = ot.exonCoordinateToChromosome(ot_start)
  ot_stop = ot.exonCoordinateToChromosome(a.targetCoordinateToQuery(stop))
  annot = lib_filter.TranscriptAnnotation(
    lib_filter.ChromosomeInterval(
      t.chromosomeInterval.chromosome,
      start,
      stop,
      t.chromosomeInterval.strand),
    t.name, [])
  annot.addLabel('outOfFrame')
  # number of out of frame codons wrt transcript T
  startCodon = min(t.chromosomeCoordinateToCodon(start),
                   t.chromosomeCoordinateToCodon(stop))
  stopCodon = max(t.chromosomeCoordinateToCodon(start),
                  t.chromosomeCoordinateToCodon(stop))
  if startCodon is not None and stopCodon is not None:
    numOOF_this = 1 + stopCodon[0] - startCodon[0]
  else:
    numOOF_this = 1
  if numOOF_this < 0:
    print 'numOOF_this < 0: %d' % numOOF_this
    print 'a: ', a.pslString()
    print 't: ', t.bedString()
    print 'ot: ', ot.bedString()
    print 'P: ', p
    print 'outOfFrameStart: ', outOfFrameStart
    print 'numIndels: ', numIndels
  assert(numOOF_this >= 0)
  # number of out of frame codons wrt transcript OT
  startCodon = min(ot.chromosomeCoordinateToCodon(ot_start),
                   ot.chromosomeCoordinateToCodon(ot_stop))
  stopCodon = max(ot.chromosomeCoordinateToCodon(ot_start),
                  ot.chromosomeCoordinateToCodon(ot_stop))
  if startCodon is not None and stopCodon is not None:
    numOOF_them = 1 + stopCodon[0] - startCodon[0]
  else:
    numOOF_them = 1
  if numOOF_them < 0:
    print 'numOOF_them < 0: %d' % numOOF_them
    print 'a: ', a.pslString()
    print 't: ', t.bedString()
    print 'ot: ', ot.bedString()
    print 'P: ', p
    print 'outOfFrameStart: ', outOfFrameStart
    print 'numIndels: ', numIndels
  assert(numOOF_them >= 0)
  annot.addLabel('outOfFrameCodonsThis_%d' % numOOF_this)
  annot.addLabel('outOfFrameCodonsThem_%d' % numOOF_them)
  # number of frame shifting indels in OT
  annot.addLabel('frameShiftingIndels_%d' % numIndels)
  t.annotations.append(annot)


def searchMutation(t, ot, i, p_ot, codon_seq, original_codon_seq, mutated_codons):
  """ for a particular position, check to see if either the transcript T or
  original transcript OT has a mutation.
  """
  codon_tup = t.mRnaCoordinateToCodon(i)  # codon tuple
  o_codon_tup = ot.chromosomeCoordinateToCodon(p_ot)
  if codon_tup is None: return None
  if o_codon_tup is None: return None
  codon = getCodon(t, codon_seq, codon_tup)
  o_codon = getCodon(ot, original_codon_seq, o_codon_tup)
  aa = lib_filter.codonToAminoAcid(codon)  # amino acid
  o_aa = lib_filter.codonToAminoAcid(o_codon)  # original amino acid
  if codon_tup[0] in mutated_codons:
    return
  mutated_codons.add(codon_tup[0])
  if t.chromosomeInterval.strand:
    codon_tup_start = (codon_tup[0], 0)  # left most position
  else:
    codon_tup_start = (codon_tup[0], 2)  # left most position
  annot = lib_filter.TranscriptAnnotation(
    lib_filter.ChromosomeInterval(
      t.chromosomeInterval.chromosome,
      t.codonCoordinateToChromosome(codon_tup_start),
      t.codonCoordinateToChromosome(codon_tup_start) + 3,
      t.chromosomeInterval.strand),
    t.name, [])
  if aa != o_aa:
    annot.addLabel('nonsynon')
    # me first - then you
    annot.addLabel('%s.%s_%s.%s' %
                   (codon, aa, o_codon, o_aa))
  else:
    annot.addLabel('synon')
    # me first - then you
    annot.addLabel('%s.%s_%s.%s' % (codon, aa, o_codon, o_aa))
  t.annotations.append(annot)


def extraArgs(parser):
  """ For arguments used in testing.
  """
  parser.add_argument(
    '--allowSingleExons', action='store_true', default=False,
    help='Processes single exon transcripts. default=%(default)s')


def main():
  args = lib_filter.boilerplateArguments(extraArgs)
  counts = Counts()
  seq_dict = lib_filter.getSequences(args.sequence, upper=True)
  original_seq_dict = lib_filter.getSequences(args.refSequence, upper=True)
  transcripts = lib_filter.getTranscripts(
    args.geneCheckBed, args.geneCheckBedDetails)
  original_transcripts = lib_filter.getTranscripts(
    args.originalGeneCheckBed, args.originalGeneCheckBedDetails)
  original_transcripts_dict = lib_filter.transcriptListToDict(
    original_transcripts, noDuplicates=True)
  alignments = lib_filter.getAlignments(args.alignment)
  alignments_dict = {}
  for a in alignments:
    key = '%s_%s' % (a.qName, a.tName)
    alignments_dict.setdefault(key, [])
    alignments_dict[key].append(a)
  counts.alignments = len(alignments_dict)
  counts.transcripts = len(transcripts)
  counts.o_transcripts = len(original_transcripts)
  counts.seqs = len(seq_dict)
  counts.o_seqs = len(original_seq_dict)
  for t in transcripts:
    if len(t.exons) == 1 and not args.allowSingleExons:
      counts.dropped_singleExons += 1
      continue
    if t.chromosomeInterval.chromosome not in seq_dict:
      counts.dropped_missingSeqs += 1
      continue
    ot = original_transcripts_dict[lib_filter.removeAlignmentNumber(t.name)]
    if ot.chromosomeInterval.chromosome not in original_seq_dict:
      counts.dropped_o_missingSeqs += 1
      continue
    t_seq = seq_dict[t.chromosomeInterval.chromosome]
    ot_seq = original_seq_dict[ot.chromosomeInterval.chromosome]
    codon_seq = t.getMRna(t_seq)
    if 'N' in codon_seq:
      counts.dropped_mRnaNs += 1
      continue
    o_codon_seq = ot.getMRna(ot_seq)
    if codon_seq == o_codon_seq:
      counts.dropped_matchingMRna += 1
      continue
    aa_seq = [lib_filter.codonToAminoAcid(c) for c
              in lib_filter.readCodons(codon_seq)]
    if aa_seq == []:
      counts.dropped_emptyAASeq += 1
      continue
    if aa_seq[0] != 'Met':
      counts.dropped_noStart += 1
      continue
    if aa_seq[-1] != 'Stop':
      counts.dropped_noStop += 1
      continue
    o_aa_seq = [lib_filter.codonToAminoAcid(c) for c
                in lib_filter.readCodons(o_codon_seq)]
    key = '%s_%s' % (lib_filter.removeAlignmentNumber(t.name),
                     t.chromosomeInterval.chromosome)
    alignments = alignments_dict[key]
    counts.aaSeqLens.append(len(aa_seq) / float(len(o_aa_seq)))
    if len(aa_seq) < 0.1 * len(o_aa_seq):
      counts.dropped_aaSeqTooShort += 1
      continue
    mutated_codons = set()
    for a in alignments:
      counts.walkAlignment += 1
      # if the psl does not cover the gene in question skip it
      if not alignmentCoversGene(a, t, len(codon_seq)):
        counts.dropped_alignmentNoCoverGene += 1
        continue
      outOfFrame = False  # keep track of when we go out and come into frame.
      outOfFrameStart = None
      outOfFrameCount = 0
      prevPositionWasNone = False  # keep track of the number of indels
      prevPositionWasJump = False  # keep track of the number of indels
      prevQ = None
      numIndels = 0
      counts.walkMRna += 1
      for i in xrange(0, len(codon_seq)):
        # walk through every position of the codon_seq and map over to the o_codon_seq
        p = t.mRnaCoordinateToChromosome(i)
        q = a.targetCoordinateToQuery(p)
        p_ot = ot.exonCoordinateToChromosome(q)
        if p is None or q is None or p_ot is None:
          # if any of the positions dont map, skip this position
          if p_ot is None and not prevPositionWasNone:
            prevPositionWasNone = True
            numIndels += 1
          continue
        if prevQ is not None and prevQ + 1 != q:
          # if there is an indel in the query sequence we'll only see it by
          # the q value jumping by greater than 1.
          numIndels += 1
        prevQ = q
        prevPositionWasNone = False
        if (t_seq.getNucleotide(
            p, complementNuc=(not t.chromosomeInterval.strand)) !=
            ot_seq.getNucleotide(
            p_ot, complementNuc=(not ot.chromosomeInterval.strand))):
          # these nucleotides are different: there is a mutation
          searchMutation(t, ot, i, p_ot, codon_seq, o_codon_seq, mutated_codons)
        codon_tup = t.mRnaCoordinateToCodon(i)  # codon tuple
        o_codon_tup = ot.chromosomeCoordinateToCodon(p_ot)
        if not outOfFrame and ((o_codon_tup is None) or (codon_tup[1] != o_codon_tup[1])):
          # we just went out of frame
          outOfFrame = True
          outOfFrameStart = p
          outOfFrameCount += 1
        elif outOfFrame and ((o_codon_tup is not None) and (codon_tup[1] == o_codon_tup[1])):
          # we just came back into frame
          outOfFrame = False
          recordOutOfFrame(a, t, ot, p, outOfFrameStart, numIndels)
          numIndels = 0
      if outOfFrame:
        # was still out of frame at the end of the mRNA
        outOfFrame = False
        recordOutOfFrame(
          a, t, ot, p, outOfFrameStart, numIndels)
        numIndels = 0
  counts.recordCounts(args)
  lib_filter.writeAllBeds(transcripts, args)


if __name__ == '__main__':
  main()
