#!/usr/bin/env python
"""
nLook
6 June 2014

dent earl, dearl a soe ucsc edu

a filter for the msca project analysis pipeline.
scans Trascripts for bad transcripts that contain Ns.
"""
from argparse import ArgumentParser
import sys
import lib_filter


def main():
  parser = ArgumentParser()
  lib_filter.initializeArguments(parser)
  args = parser.parse_args()
  lib_filter.checkArguments(args, parser)
  seq_dict = lib_filter.getSequences(args.sequence, upper=True)
  chrom_dict = lib_filter.getChromSizes(args.chromSizes)
  bed_file = open(args.geneCheckBed, 'r')
  bed_details_file = open(args.geneCheckBedDetails, 'r')
  transcripts = []
  for t in lib_filter.transcriptIterator(bed_file, bed_details_file):
    transcripts.append(t)
    for annot in t.annotations:
      chrom = annot.chromosomeInterval.chromosome
      start = annot.chromosomeInterval.start
      stop = annot.chromosomeInterval.stop
      seq = seq_dict[chrom].sliceSequence(start, stop)
      if 'N' in seq:
        annot.addLabel('containsNs')
  lib_filter.writeAllBeds(transcripts, args)


if __name__ == '__main__':
  main()
