#!/usr/bin/env python
"""
paralogs
23 June 2014

dent earl, dearl a soe ucsc edu

a filter for the msca project analysis pipeline.
scans Trascripts and PSLs for transcript alignments located in multiple
locations and labels them as paralogous.
"""
import sys
import lib_filter


def reduceTranscripts(transcripts):
  """ reduce the list of transcripts down to a list of Transcript objects
  where there is one list per NAME. Returns a dict of lists. Key is
  transcript name, value is list of transcripts
  """
  reduced = {}
  for t in transcripts:
    if t.name not in reduced:
      reduced[t.name] = []
    reduced[t.name].append(t)
  return reduced


def hasOkCopy(this, transcriptList):
  """ given a transcript THIS and a list of transcripts which contains
  THIS, determine if there is a non-THIS transcript that is OK.
  """
  count = 0
  for t in transcriptList:
    isOk = True
    if this == t:
      continue
    if t.annotations == []:
      count += 1
      continue
    for annot in t.annotations:
      for label in annot.labels:
        if (label != 'hasOkCopies' and
            label != 'hasBadCopies' and
            not label.startswith('count_')):
          isOk = False
    if isOk:
      # this transcript is ok
      count += 1
  return count


def hasBadCopy(this, transcriptList):
  """ given a transcript THIS and a list of transcripts which contains
  THIS, determine if there is a non-THIS transcript that is BAD.
  """
  # note there is code duplication here but this is sufficiently confusing when
  # written in a general fashion to justify duplication.
  count = 0
  for t in transcriptList:
    isBad = False
    if this == t:
      continue
    for annot in t.annotations:
      for label in annot.labels:
        if (label != 'hasOkCopies' and
            label != 'hasBadCopies' and
            not label.startswith('count_')):
          isBad = True
    if isBad:
      # this transcript is bad
      count += 1
  return count


def main():
  args = lib_filter.boilerplateArguments()
  transcripts = lib_filter.getTranscripts(
    args.geneCheckBed, args.geneCheckBedDetails)
  uniqueTranscripts = reduceTranscripts(transcripts)
  for t in transcripts:
    count = hasOkCopy(t, uniqueTranscripts[t.name])
    if count:
      if t.annotations == []:
        # OK transcripts could have no annotations
        t.annotations.append(
          lib_filter.TranscriptAnnotation(t.chromosomeInterval, t.name, []))
      for annot in t.annotations:
        annot.addLabel('hasOkCopies')
        annot.addLabel('count_%d' % count)
    count = hasBadCopy(t, uniqueTranscripts[t.name])
    if count:
      if t.annotations == []:
        # OK transcripts could have no annotations
        t.annotations.append(
          lib_filter.TranscriptAnnotation(t.chromosomeInterval, t.name, []))
      for annot in t.annotations:
        annot.addLabel('hasBadCopies')
        annot.addLabel('count_%d' % count)
  lib_filter.writeAllBeds(transcripts, args)


if __name__ == '__main__':
  main()
